spring:
 redis:
   host: 127.0.0.1
   port: 6379
   database: 0
   password:
 datasource:

  url: jdbc:oracle:thin:@127.0.0.1:1521:orcl2018
  username: gzh
  password: gzh
  driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.demo.bean
